POST http://localhost:8080/request-body-string
Content-Type: text/plain

hello!

###
POST http://localhost:8080/request-param
Content-Type: application/x-www-form-urlencoded

username=kim&age=20

###
GET http://localhost:8080/request-header?username=hello

###
GET http://localhost:8080/request-param?username=hello&age=20

